version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      
    ports:
      - "12346:12346"
    networks:
      - default

  db:
    build: 
      context: .
      dockerfile: db.dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - default
   
volumes:
  db-data:

networks:
  default:
    driver: bridge